### ISSUE TITLE
Is loading translations at build time is possible?

### ISSUE THREAD

**Issue by burakkgunduzz** [QuiiBz/next-international#103]
Is it possible to load translations at build time without using getServerSideProps or GetStaticProps or client side load?

**Comment by QuiiBz** [comment]
This is not possible because `getServerSideProps`, `getStaticProps`, or client-side `fetch` are the only ways to load the correct locale based on what the user needs. What's your use case?

**Comment by burakkgunduzz** [comment]
Well, I do not want to use getServerSideProps since I face with really long cold starts some time (such as 10-15 seconds). Therefore, my pages are not using next.js data fetching methods right now. In order to keep my pages fast, I can load translations client side but that is not ideal since it cause flickering when refresh. On the other hand, using a fallback and waiting translations to be load in client side can hurt page performance and SEO I think. Thus, I am really in a though situation and do not sure how to go? @QuiiBz

**Comment by QuiiBz** [comment]
As I said before, these (`getServerSideProps`, `getStaticProps`, client-side) are the only solutions provided by Next.js to load data. We can't do anything more at our level, so I'll recommend loading them on the client and using a fallback locale. This shouldn't hurt a lot SEO, since won't have to wait for loading the locale (which should be very fast) because it uses a fallback locale.

**Comment by burakkgunduzz** [comment]
Thank you!
