### ISSUE TITLE
a question : if i have large translation...does all translation load for all pages? 

### ISSUE THREAD

**Issue by zakidze** [QuiiBz/next-international#180]
if i have translation...does all translation load for all pages? 

example i m at landing page does about  translation  get loaded?????

**Comment by QuiiBz** [comment]
I'm not sure to understand correctly your question, but to explain a bit:

- On the server, all translation files are loaded, because it's faster and doesn't impact the client bundle size
- On the client, only the translation file for the current locale is loaded. If you're on the `/en` URL, only the english translation file is loaded

**Comment by zakidze** [comment]
say i have 4 pages in my app
landing page
about page
contact page
marketplace page


i have both EN And DE  for each pages translation tags

landingpageEn.json
aboutpageEn.json
marketplaceEn.json

landingpageDe.json
aboutpageDe.json
marketplaceDe.json


say i navigate to landing page does about.json and marketplace get loaded?

anathor question are thoes translation at request time or build time?????
