### ISSUE TITLE
Is defaultLocale necessary?

### ISSUE THREAD

**Issue by zackrw** [QuiiBz/next-international#194]
No problem, just a discussion question about a potential optimization:

* Is there a reason that "defaultLocale" can't just always be the first one in the locales array? 
* I could imagine someone wanting to order those alphabetically, but even when that means not putting the default first?

**Comment by gustaveWPM** [comment]
lol, that was somehow what I was doing

```ts
export const getEnumKeys = (e: object): string[] => Object.keys(e).filter((key) => isNaN(Number(key)));
export const getEnumFirstKey = (e: object): string => getEnumKeys(e)[0];
```

```ts
export enum ELanguagesFlag {
  fr,
  en
}

export const LANGUAGES: LanguageFlag[] = getEnumKeys(ELanguagesFlag) as LanguageFlag[];
export const DEFAULT_LANGUAGE: LanguageFlag = getEnumFirstKey(ELanguagesFlag) as LanguageFlag;
```

But I dropped it.

**Comment by QuiiBz** [comment]
> Is there a reason that "defaultLocale" can't just always be the first one in the locales array?

The reason is that it's (in my opinion) better to explicitly define which locale is the default because it's visually easier to understand what's going on. Someone that doesn't know anything about next-international will immediately understand how it works.

That's certainly debatable, but I'll close this issue as we want this library to be simple and straightforward. Thanks for the suggestion though!
