### ISSUE TITLE
Manual control of the needed locale

### ISSUE THREAD

**Issue by Marsony** [QuiiBz/next-international#261]
**Is your feature request related to a problem? Please describe.**
We are faced with a situation where we cannot use the locales themselves in Next. I mean that we can't use i18n object in the next.config.js. This is due to the limit of available languages count (100), and we support a sufficient number of countries and languages and process this using routes. (/en-EN, etc, over than 160+ pairs in summary). Also your library is requires to use `defaultLocale` in i18n

**Describe the solution you'd like**
Is it possible to get locales inside server functions? For example, right now `next-international` requires to use getServerSideProps inside getLocaleProps and we can't control the locale which we need to return because you extract `locale` from the `nextjs i18n`.

**Describe alternatives you've considered**
Maybe some `getTranslations(props: { locale: string })` method

P.S. we using pages router

**Comment by QuiiBz** [comment]
This seems a bit related to #229 - we now expose the internal `createT` function that is used to construct the `useI18n` / `useScopedI18n` hooks. It's not documented as it's a very niche use-case, but you can check out the source code directly (it's not very complex to use): https://github.com/QuiiBz/next-international/blob/main/packages/next-international/src/common/create-use-i18n.ts

**Comment by Marsony** [comment]
> This seems a bit related to #229 - we now expose the internal `createT` function that is used to construct the `useI18n` / `useScopedI18n` hooks. It's not documented as it's a very niche use-case, but you can check out the source code directly (it's not very complex to use): https://github.com/QuiiBz/next-international/blob/main/packages/next-international/src/common/create-use-i18n.ts

Can you please provide minimal repro or maybe example? Would like to understand ideas for implementation.

**Comment by QuiiBz** [comment]
As I said we don't have any documentation on it since it's a niche use case, and for an example you can take a look at the code I linked above . `createT` returns a `useI18n` / `useScopedI18n` function based on if you pass it a scope in second argument.

I don't have access to your current app, so I can't really give you more details on how to use it :/

**Comment by QuiiBz** [comment]
Closing for now, happy to re-open and help when we have more information.

**Comment by gustaveWPM** [comment]
Well... I could be interested too.

So far I've structured my code so that locale files contain a `label` field, and I'm about to write my "Language Switcher" component. I'm going to use these `label` fields.

I could just easily make an object that contains each _language flag_ as key, and each associated label as value, but I'm a bit embarrassed about defining vocabulary outside the locales files.

I'll probably create an issue on the same topic.
