### ISSUE TITLE
'Unsupported locale error' on routes not matched by middleware.

### ISSUE THREAD

**Issue by Willem-Jaap** [QuiiBz/next-international#340]
My setup is as described in the documentation
```txt
src/app
├── [locale]
│   ├── layout.tsx
│   └── page.tsx
```

The layout contains the following code: 
```tsx
import { I18nProviderClient } from '~locales/client';

interface Props {
    children: ReactNode;
    params: { locale: string };
}

const Layout = ({ children, params }: Props) => {
    console.log('Layout', params);

    return <I18nProviderClient locale={params.locale}>{children}</I18nProviderClient>;
};

export default Layout;
```

However, this locale prop also receives `favicon.ico` in the locale property.
```bash
>  Layout { locale: 'favicon.ico' }
```

Next-international also logs the following error `[next-international] The locale 'favicon.ico' is not supported. Defined locales are: [en, nl].`

The favicon is not matched in the middleware, just like in the docs (https://next-international.vercel.app/docs/app-setup#setup-middleware)

**To Reproduce**
I don't think this is repository specific, but you can clone https://github.com/pixel-perfect-agency/next-foundation

**Expected behavior**
Favicon and other routes ignored in middleware matcher should not be perceived as locales

**About:**
 - next-international version [e.g. 1.2.3]
 - Next.js version [e.g. 14.1.0]

**Comment by QuiiBz** [comment]
Is your favicon located inside the `[locale]` folder? Otherwise if it's not ignored but should be as specified in your middleware configuration, I believe it's a Next.js bug.

**Comment by QuiiBz** [comment]
This is usually caused by:
1) the middleware being miss-configured
2) the `favicon.ico` file being placed inside the `[locale]` folder, which should instead be inside the `app` (or `src`) folder

Could you share more context on your app?

> I am using rewrite as the mapping strategy, when navigating to a page should I append the current locale to the start of the href?

This is done automatically by the middleware if you don't do it manually.

**Comment by 2Senn** [comment]
I have the middleware exactly as it is in the docs. My favicon is not in the locale folder. I think the problem is mainly for the home page "/" since everything else works fine. 

I have an api that gets called on the main page route and for some reason it does not get called. I have an api directory for next auth in my app directory but not inside the [locale] route. Could this be causing issues?

**Comment by dariolongo-dufercodev** [comment]
Hi,
@2Senn I've the same problema, how do you solve this? why is related to next.js config?
Thanks
