### ISSUE TITLE
 Error: "Locale not found" in api nextjs routes

### ISSUE THREAD

**Issue by malkavi6** [QuiiBz/next-international#97]
Please exclude language support from api nextjs routing.

Despite excluding api nextjs routing in the middleware, when calling the api, I get the following error:
```
error node_modules/next-international/dist/app/client/index.js (1:3156) @ eval
- error Error: Locale not found
```

**Comment by Yovach** [comment]
Hi, I don't know if this is the right place but my issue is quite similar to this because it concerns `middleware`.

Currently, [Metadata Files](https://nextjs.org/docs/app/api-reference/file-conventions/metadata) are handled when they shouldn't (depite adding `'/((?!robots.txt).*)'` to `config.matcher`).

Moving `robots.tsx` in `[locale]` isn't working too.. :/

**Comment by QuiiBz** [comment]
@malkavi6 could you share a reproduction? This error occurs when you call `useCurrentLocale` but the locale can't be found. `useCurrentLocale` shouldn't be used inside API routes.

@Yovach you could also update the middleware config to exclude these static files:

```ts
export const config = {
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico|sitemap.xml|robots.txt|manifest.webmanifest).*)'],
}
```

**Comment by Yovach** [comment]
> @Yovach you could also update the middleware config to exclude these static files:
> 
> ```ts
> export const config = {
>   matcher: ['/((?!api|_next/static|_next/image|favicon.ico|sitemap.xml|robots.txt|manifest.webmanifest).*)'],
> }
> ```

Oh, that seems to work with everything on one line, thanks.

**Comment by malkavi6** [comment]
True, my mistake. I used useCurrentLocale in route api..
I don't see any errors. Thanks for the help.
